-- ════════════════════════════════════════════════════════════════════
-- Della Pace · Receitas (FICHA TÉCNICA · Title Case)
-- Roda APÓS import-historico.sql.
-- ════════════════════════════════════════════════════════════════════
SET NAMES utf8mb4;

-- ═══ 1. STOCK_ITEMS placeholder (26 ingredientes) ════
INSERT IGNORE INTO stock_items (id, name, brand, supplier, unit_price, quantity, unit, min_quantity, notes) VALUES
  ('stk-abobrinha', 'Abobrinha', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-alho-poro', 'Alho Poró', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-azeite', 'Azeite', '', '', 0, 0, 'L', 0, 'auto-criado pela importação'),
  ('stk-azeitona', 'Azeitona', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-bacon', 'Bacon', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-calabresa', 'Calabresa', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-catupiry', 'Catupiry', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-cebola', 'Cebola', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-champignon', 'Champignon', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-embalagem', 'Embalagem', '', '', 0, 0, 'un', 0, 'auto-criado pela importação'),
  ('stk-ervilha', 'Ervilha', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-farinha-de-trigo', 'Farinha de Trigo', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-fermento-seco', 'Fermento Seco', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-frango', 'Frango', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-gorgonzola', 'Gorgonzola', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-lombinho-canadense', 'Lombinho Canadense', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-manjericao', 'Manjericão', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-molho-de-tomate', 'Molho de Tomate', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-mussarela', 'Mussarela', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-oregano', 'Orégano', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-ovo', 'Ovo', '', '', 0, 0, 'un', 0, 'auto-criado pela importação'),
  ('stk-parmesao-ralado', 'Parmesão Ralado', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-presunto', 'Presunto', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-sal', 'Sal', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-tomate-cereja', 'Tomate Cereja', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação'),
  ('stk-agua', 'Água', '', '', 0, 0, 'L', 0, 'auto-criado pela importação');

-- ═══ 2. LIMPA receitas antigas dos sabores importados ════════════════
DELETE FROM recipe_ingredients WHERE menu_item_id IN ('margueritha','calabria','zucchinni-e-bacon','4-fromaggio','lombinho-com-alho-poro','frango-com-catupiry','portuguesa','toscana');

-- ═══ 3. RECIPE_INGREDIENTS ═══════════════════════════════════════════
INSERT INTO recipe_ingredients (menu_item_id, stock_item_id, product_id, amount, unit) VALUES
  ('calabria', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('calabria', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('calabria', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('calabria', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('calabria', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('calabria', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('calabria', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.16, 'kg'),
  ('calabria', 'stk-calabresa', (SELECT id FROM products WHERE LOWER(name) = LOWER('Calabresa') LIMIT 1), 0.1, 'kg'),
  ('calabria', 'stk-cebola', (SELECT id FROM products WHERE LOWER(name) = LOWER('Cebola') LIMIT 1), 0.05, 'kg'),
  ('calabria', 'stk-azeitona', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeitona') LIMIT 1), 0.01, 'kg'),
  ('calabria', 'stk-oregano', (SELECT id FROM products WHERE LOWER(name) = LOWER('Orégano') LIMIT 1), 0.0, 'kg'),
  ('calabria', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un'),
  ('zucchinni-e-bacon', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('zucchinni-e-bacon', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('zucchinni-e-bacon', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('zucchinni-e-bacon', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('zucchinni-e-bacon', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('zucchinni-e-bacon', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('zucchinni-e-bacon', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.16, 'kg'),
  ('zucchinni-e-bacon', 'stk-abobrinha', (SELECT id FROM products WHERE LOWER(name) = LOWER('Abobrinha') LIMIT 1), 0.1, 'kg'),
  ('zucchinni-e-bacon', 'stk-bacon', (SELECT id FROM products WHERE LOWER(name) = LOWER('Bacon') LIMIT 1), 0.05, 'kg'),
  ('zucchinni-e-bacon', 'stk-gorgonzola', (SELECT id FROM products WHERE LOWER(name) = LOWER('Gorgonzola') LIMIT 1), 0.02, 'kg'),
  ('zucchinni-e-bacon', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un'),
  ('4-fromaggio', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('4-fromaggio', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('4-fromaggio', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('4-fromaggio', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('4-fromaggio', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('4-fromaggio', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('4-fromaggio', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.13, 'kg'),
  ('4-fromaggio', 'stk-parmesao-ralado', (SELECT id FROM products WHERE LOWER(name) = LOWER('Parmesão Ralado') LIMIT 1), 0.02, 'lata'),
  ('4-fromaggio', 'stk-catupiry', (SELECT id FROM products WHERE LOWER(name) = LOWER('Catupiry') LIMIT 1), 0.02, 'kg'),
  ('4-fromaggio', 'stk-gorgonzola', (SELECT id FROM products WHERE LOWER(name) = LOWER('Gorgonzola') LIMIT 1), 0.03, 'kg'),
  ('4-fromaggio', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un'),
  ('margueritha', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('margueritha', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('margueritha', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('margueritha', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('margueritha', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('margueritha', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('margueritha', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.16, 'kg'),
  ('margueritha', 'stk-tomate-cereja', (SELECT id FROM products WHERE LOWER(name) = LOWER('Tomate Cereja') LIMIT 1), 0.05, 'kg'),
  ('margueritha', 'stk-parmesao-ralado', (SELECT id FROM products WHERE LOWER(name) = LOWER('Parmesão Ralado') LIMIT 1), 0.01, 'kg'),
  ('margueritha', 'stk-manjericao', (SELECT id FROM products WHERE LOWER(name) = LOWER('Manjericão') LIMIT 1), 0.005, 'kg'),
  ('margueritha', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un'),
  ('lombinho-com-alho-poro', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('lombinho-com-alho-poro', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('lombinho-com-alho-poro', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('lombinho-com-alho-poro', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('lombinho-com-alho-poro', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('lombinho-com-alho-poro', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('lombinho-com-alho-poro', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.1, 'kg'),
  ('lombinho-com-alho-poro', 'stk-lombinho-canadense', (SELECT id FROM products WHERE LOWER(name) = LOWER('Lombinho Canadense') LIMIT 1), 0.08, 'kg'),
  ('lombinho-com-alho-poro', 'stk-alho-poro', (SELECT id FROM products WHERE LOWER(name) = LOWER('Alho Poró') LIMIT 1), 0.04, 'kg'),
  ('lombinho-com-alho-poro', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un'),
  ('frango-com-catupiry', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('frango-com-catupiry', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('frango-com-catupiry', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('frango-com-catupiry', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('frango-com-catupiry', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('frango-com-catupiry', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('frango-com-catupiry', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.1, 'kg'),
  ('frango-com-catupiry', 'stk-frango', (SELECT id FROM products WHERE LOWER(name) = LOWER('Frango') LIMIT 1), 0.12, 'kg'),
  ('frango-com-catupiry', 'stk-catupiry', (SELECT id FROM products WHERE LOWER(name) = LOWER('Catupiry') LIMIT 1), 0.05, 'kg'),
  ('frango-com-catupiry', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un'),
  ('portuguesa', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('portuguesa', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('portuguesa', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('portuguesa', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('portuguesa', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('portuguesa', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('portuguesa', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.16, 'kg'),
  ('portuguesa', 'stk-tomate-cereja', (SELECT id FROM products WHERE LOWER(name) = LOWER('Tomate Cereja') LIMIT 1), 0.05, 'kg'),
  ('portuguesa', 'stk-presunto', (SELECT id FROM products WHERE LOWER(name) = LOWER('Presunto') LIMIT 1), 0.08, 'kg'),
  ('portuguesa', 'stk-cebola', (SELECT id FROM products WHERE LOWER(name) = LOWER('Cebola') LIMIT 1), 0.03, 'kg'),
  ('portuguesa', 'stk-ovo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Ovo') LIMIT 1), 0.5, 'un'),
  ('portuguesa', 'stk-ervilha', (SELECT id FROM products WHERE LOWER(name) = LOWER('Ervilha') LIMIT 1), 0.02, 'kg'),
  ('portuguesa', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un'),
  ('toscana', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('Farinha de Trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('toscana', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('Água') LIMIT 1), 0.12, 'kg'),
  ('toscana', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('Fermento Seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('toscana', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('Sal') LIMIT 1), 0.005, 'kg'),
  ('toscana', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeite') LIMIT 1), 0.006, 'kg'),
  ('toscana', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('Molho de Tomate') LIMIT 1), 0.05, 'kg'),
  ('toscana', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('Mussarela') LIMIT 1), 0.1, 'kg'),
  ('toscana', 'stk-champignon', (SELECT id FROM products WHERE LOWER(name) = LOWER('Champignon') LIMIT 1), 0.05, 'kg'),
  ('toscana', 'stk-bacon', (SELECT id FROM products WHERE LOWER(name) = LOWER('Bacon') LIMIT 1), 0.08, 'kg'),
  ('toscana', 'stk-azeitona', (SELECT id FROM products WHERE LOWER(name) = LOWER('Azeitona') LIMIT 1), 0.03, 'kg'),
  ('toscana', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('Embalagem') LIMIT 1), 1.0, 'un');

-- ════════════════════════════════════════════════════════════════════
-- ✓ 8 receitas, 89 ingrediente-receitas.
-- ════════════════════════════════════════════════════════════════════
