-- ════════════════════════════════════════════════════════════════════
-- Della Pace · Receitas (FICHA TÉCNICA do Aurélio)
-- Idempotente. Roda APÓS import-historico.sql.
-- ════════════════════════════════════════════════════════════════════
SET NAMES utf8mb4;

-- ═══ 1. STOCK_ITEMS placeholder (pra satisfazer FK do recipe_ingredients) ═══
INSERT IGNORE INTO stock_items (id, name, brand, supplier, unit_price, quantity, unit, min_quantity, notes) VALUES
  ('stk-farinha-de-trigo', 'farinha de trigo', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-agua', 'água', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-fermento-seco', 'fermento seco', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-sal', 'sal', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-azeite', 'azeite', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-molho-de-tomate', 'molho de tomate', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-mussarela', 'mussarela', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-calabresa', 'calabresa', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-cebola', 'cebola', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-azeitona', 'azeitona', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-oregano', 'orégano', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-embalagem', 'embalagem', '', '', 0, 0, 'un', 0, 'auto-criado pela importação de receitas'),
  ('stk-abobrinha', 'abobrinha', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-bacon', 'bacon', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-gorgonzola', 'gorgonzola', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-parmesao-ralado', 'parmesão ralado', '', '', 0, 0, 'lata', 0, 'auto-criado pela importação de receitas'),
  ('stk-catupiry', 'catupiry', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-tomate-cereja', 'tomate cereja', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-manjericao', 'manjericão', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-lombinho-canadense', 'lombinho canadense', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-alho-poro', 'alho poró', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-frango', 'frango', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-presunto', 'presunto', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-ovo', 'ovo', '', '', 0, 0, 'un', 0, 'auto-criado pela importação de receitas'),
  ('stk-ervilha', 'ervilha', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas'),
  ('stk-champignon', 'champignon', '', '', 0, 0, 'kg', 0, 'auto-criado pela importação de receitas');

-- ═══ 2. LIMPA receitas antigas dos sabores importados ════════════════
DELETE FROM recipe_ingredients WHERE menu_item_id IN ('margueritha','calabria','zucchinni-e-bacon','4-fromaggio','lombinho-com-alho-poro','frango-com-catupiry','portuguesa','toscana');

-- ═══ 3. RECIPE_INGREDIENTS (8 receitas) ═══════════════════════════════
INSERT INTO recipe_ingredients (menu_item_id, stock_item_id, product_id, amount, unit) VALUES
  ('calabria', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('calabria', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('calabria', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('calabria', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('calabria', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('calabria', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('calabria', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.16, 'kg'),
  ('calabria', 'stk-calabresa', (SELECT id FROM products WHERE LOWER(name) = LOWER('calabresa') LIMIT 1), 0.1, 'kg'),
  ('calabria', 'stk-cebola', (SELECT id FROM products WHERE LOWER(name) = LOWER('cebola') LIMIT 1), 0.05, 'kg'),
  ('calabria', 'stk-azeitona', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeitona') LIMIT 1), 0.01, 'kg'),
  ('calabria', 'stk-oregano', (SELECT id FROM products WHERE LOWER(name) = LOWER('orégano') LIMIT 1), 0.0, 'kg'),
  ('calabria', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un'),
  ('zucchinni-e-bacon', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('zucchinni-e-bacon', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('zucchinni-e-bacon', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('zucchinni-e-bacon', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('zucchinni-e-bacon', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('zucchinni-e-bacon', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('zucchinni-e-bacon', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.16, 'kg'),
  ('zucchinni-e-bacon', 'stk-abobrinha', (SELECT id FROM products WHERE LOWER(name) = LOWER('abobrinha') LIMIT 1), 0.1, 'kg'),
  ('zucchinni-e-bacon', 'stk-bacon', (SELECT id FROM products WHERE LOWER(name) = LOWER('bacon') LIMIT 1), 0.05, 'kg'),
  ('zucchinni-e-bacon', 'stk-gorgonzola', (SELECT id FROM products WHERE LOWER(name) = LOWER('gorgonzola') LIMIT 1), 0.02, 'kg'),
  ('zucchinni-e-bacon', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un'),
  ('4-fromaggio', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('4-fromaggio', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('4-fromaggio', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('4-fromaggio', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('4-fromaggio', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('4-fromaggio', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('4-fromaggio', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.13, 'kg'),
  ('4-fromaggio', 'stk-parmesao-ralado', (SELECT id FROM products WHERE LOWER(name) = LOWER('parmesão ralado') LIMIT 1), 0.02, 'lata'),
  ('4-fromaggio', 'stk-catupiry', (SELECT id FROM products WHERE LOWER(name) = LOWER('catupiry') LIMIT 1), 0.02, 'kg'),
  ('4-fromaggio', 'stk-gorgonzola', (SELECT id FROM products WHERE LOWER(name) = LOWER('gorgonzola') LIMIT 1), 0.03, 'kg'),
  ('4-fromaggio', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un'),
  ('margueritha', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('margueritha', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('margueritha', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('margueritha', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('margueritha', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('margueritha', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('margueritha', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.16, 'kg'),
  ('margueritha', 'stk-tomate-cereja', (SELECT id FROM products WHERE LOWER(name) = LOWER('tomate cereja') LIMIT 1), 0.05, 'kg'),
  ('margueritha', 'stk-parmesao-ralado', (SELECT id FROM products WHERE LOWER(name) = LOWER('parmesão ralado') LIMIT 1), 0.01, 'kg'),
  ('margueritha', 'stk-manjericao', (SELECT id FROM products WHERE LOWER(name) = LOWER('manjericão') LIMIT 1), 0.005, 'kg'),
  ('margueritha', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un'),
  ('lombinho-com-alho-poro', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('lombinho-com-alho-poro', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('lombinho-com-alho-poro', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('lombinho-com-alho-poro', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('lombinho-com-alho-poro', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('lombinho-com-alho-poro', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('lombinho-com-alho-poro', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.1, 'kg'),
  ('lombinho-com-alho-poro', 'stk-lombinho-canadense', (SELECT id FROM products WHERE LOWER(name) = LOWER('lombinho canadense') LIMIT 1), 0.08, 'kg'),
  ('lombinho-com-alho-poro', 'stk-alho-poro', (SELECT id FROM products WHERE LOWER(name) = LOWER('alho poró') LIMIT 1), 0.04, 'kg'),
  ('lombinho-com-alho-poro', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un'),
  ('frango-com-catupiry', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('frango-com-catupiry', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('frango-com-catupiry', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('frango-com-catupiry', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('frango-com-catupiry', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('frango-com-catupiry', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('frango-com-catupiry', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.1, 'kg'),
  ('frango-com-catupiry', 'stk-frango', (SELECT id FROM products WHERE LOWER(name) = LOWER('frango') LIMIT 1), 0.12, 'kg'),
  ('frango-com-catupiry', 'stk-catupiry', (SELECT id FROM products WHERE LOWER(name) = LOWER('catupiry') LIMIT 1), 0.05, 'kg'),
  ('frango-com-catupiry', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un'),
  ('portuguesa', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('portuguesa', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('portuguesa', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('portuguesa', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('portuguesa', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('portuguesa', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('portuguesa', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.16, 'kg'),
  ('portuguesa', 'stk-tomate-cereja', (SELECT id FROM products WHERE LOWER(name) = LOWER('tomate cereja') LIMIT 1), 0.05, 'kg'),
  ('portuguesa', 'stk-presunto', (SELECT id FROM products WHERE LOWER(name) = LOWER('presunto') LIMIT 1), 0.08, 'kg'),
  ('portuguesa', 'stk-cebola', (SELECT id FROM products WHERE LOWER(name) = LOWER('cebola') LIMIT 1), 0.03, 'kg'),
  ('portuguesa', 'stk-ovo', (SELECT id FROM products WHERE LOWER(name) = LOWER('ovo') LIMIT 1), 0.5, 'un'),
  ('portuguesa', 'stk-ervilha', (SELECT id FROM products WHERE LOWER(name) = LOWER('ervilha') LIMIT 1), 0.02, 'kg'),
  ('portuguesa', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un'),
  ('toscana', 'stk-farinha-de-trigo', (SELECT id FROM products WHERE LOWER(name) = LOWER('farinha de trigo') LIMIT 1), 0.21000000000000002, 'kg'),
  ('toscana', 'stk-agua', (SELECT id FROM products WHERE LOWER(name) = LOWER('água') LIMIT 1), 0.12, 'kg'),
  ('toscana', 'stk-fermento-seco', (SELECT id FROM products WHERE LOWER(name) = LOWER('fermento seco') LIMIT 1), 0.0006000000000000001, 'kg'),
  ('toscana', 'stk-sal', (SELECT id FROM products WHERE LOWER(name) = LOWER('sal') LIMIT 1), 0.005, 'kg'),
  ('toscana', 'stk-azeite', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeite') LIMIT 1), 0.006, 'kg'),
  ('toscana', 'stk-molho-de-tomate', (SELECT id FROM products WHERE LOWER(name) = LOWER('molho de tomate') LIMIT 1), 0.05, 'kg'),
  ('toscana', 'stk-mussarela', (SELECT id FROM products WHERE LOWER(name) = LOWER('mussarela') LIMIT 1), 0.1, 'kg'),
  ('toscana', 'stk-champignon', (SELECT id FROM products WHERE LOWER(name) = LOWER('champignon') LIMIT 1), 0.05, 'kg'),
  ('toscana', 'stk-bacon', (SELECT id FROM products WHERE LOWER(name) = LOWER('bacon') LIMIT 1), 0.08, 'kg'),
  ('toscana', 'stk-azeitona', (SELECT id FROM products WHERE LOWER(name) = LOWER('azeitona') LIMIT 1), 0.03, 'kg'),
  ('toscana', 'stk-embalagem', (SELECT id FROM products WHERE LOWER(name) = LOWER('embalagem') LIMIT 1), 1.0, 'un');

-- ════════════════════════════════════════════════════════════════════
-- ✓ Importação completa. 8 receitas, 89 ingredientes.
-- ════════════════════════════════════════════════════════════════════
